def choose_function():
    print("Made by Jakub Kalinowski & Piotr Marszałek")
    print("Choose your function:")
    print("1. x^3 - 6x^2 +7x - 3")
    print("2. sin(x)")
    print("3. cos(x)")
    print("4. 5^x - 3")
    print("5. 4^(3 cos(2x)) - 1")
    print("6. sin(x)/x")
    print("7. sin(2x^2 - 2) - 3x^3 + 2x^2 - 1")
